### 01-01 What is ML?

Features + Target -> ML -> Model

Then, Features + Model -> Predictions

### 01-02 ML vs. Rules

Converting to numbers

Predictions as probability


### 01-03 Supervised ML

Supervised ML:
g(X) ≈ y

Regression, Binary Classification, Multiclass Classification, Ranking

### 01-04 CRISP-DM

![CRISP-DM](crisp-dm.png)

### 01-05 Model Selection

60% Training <br>
20% Validation <br>

-- Select best model --<br>
-- Train on both train and val --

20% Testing <br><br>


Process:
1. Split
2. Train
3. Val
4. Select the best
5. Test
6. Check

### 01-07 Numpy

In [1]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
list = [1, 2, 3, 4, 5]

np.array(list)

array([1, 2, 3, 4, 5])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1st number to include, 2nd number to include, number of samples
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Multi-dimensional arrays

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
n[0, 1]

np.int64(2)

In [19]:
n[2]

array([7, 8, 9])

In [20]:
n[:, 1]

array([2, 5, 8])

In [21]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Random arrays

In [26]:
np.random.seed(42)
np.random.rand(5, 2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [27]:
np.random.seed(42)
np.random.randn(5,2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004]])

In [28]:
np.random.seed(42)
np.random.randint(low=0, high=10, size=(5,2))

array([[6, 3],
       [7, 4],
       [6, 9],
       [2, 6],
       [7, 4]])

#### Element-wise operations

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [30]:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
b =(10 + (a * 2)) ** 2 / 100

In [38]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

#### Comparison operations

In [34]:
a

array([0, 1, 2, 3, 4])

In [35]:
a >= 2

array([False, False,  True,  True,  True])

In [39]:
a >= b

array([False, False,  True,  True,  True])

In [40]:
a[a >= b]

array([2, 3, 4])

#### Summarising operations

In [41]:
a.min()

np.int64(0)

In [42]:
a.max()

np.int64(4)

In [43]:
a.sum()

np.int64(10)

In [44]:
a.mean()

np.float64(2.0)

In [45]:
a.std()

np.float64(1.4142135623730951)

In [46]:
n.sum()

np.int64(45)

### 01-08 Linear algebra

In [48]:
u = np.array([2, 4, 5 ,6])
u

array([2, 4, 5, 6])

In [49]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [50]:
u + v

array([3, 4, 5, 8])

In [51]:
# Vector-vector multiplication (dot product or inner product)

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [52]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [53]:
u.dot(v)

np.int64(14)

In [57]:
# Matrix-vector multiplication

def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result


In [56]:
# Capital letter to denote matrix

U = np.array(
    [
        [2, 4, 5, 6],
        [1, 2, 1, 2],
        [3, 1, 2, 1]    
    ]
)

U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [58]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [59]:
U.dot(v)

array([14,  5,  5])

In [63]:
# Matrix-matrix multiplication

def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]   
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        # Get the i-th column of V
        Vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, Vi)
        result[:, i] = Uvi

    return result


In [62]:
V = np.array(
    [
        [1, 1, 2],
        [0, 0.5, 1],
        [0, 2, 1],
        [2, 1, 0]
    ]
)

V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [64]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [65]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

#### Identity matrix

In [67]:
I = np.eye(3)

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [69]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [72]:
Vs = V[[0, 1, 2]]

Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [74]:
Vs_inv = np.linalg.inv(Vs)

Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [75]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 01-09 Pandas